import { faCarrot, faFish, faEgg, faCheese, faBreadSlice, faDrumstickBite, faLeaf, faWineBottle, faAppleAlt, faPepperHot, faLemon, faCookie, faIceCream, faSeedling, faTint, faUtensilSpoon, faBacon, faMortarPestle, faGlassWater, faBottleWater } from '@fortawesome/free-solid-svg-icons';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export const ingredientIcons: Record<string, IconDefinition> = {
  'Авокадо': faAppleAlt,
  'Баклажаны': faCarrot,
  'Белое вино': faWineBottle,
  'Бешамель': faMortarPestle,
  'Бульон': faUtensilSpoon,
  'Виноградные листья': faLeaf,
  'Виноградный сок': faGlassWater,
  'Говядина': faDrumstickBite,
  'Грибы': faSeedling,
  'Зелень': faLeaf,
  'Имбирь': faPepperHot,
  'Кабачки': faCarrot,
  'Какао': faBottleWater,
  'Капуста': faLeaf,
  'Картофель': faCarrot,
  'Кинза': faLeaf,
  'Кориандр': faMortarPestle,
  'Кофе': faTint,
  'Креветки': faFish,
  'Куриное филе': faDrumstickBite,
  'Курица': faDrumstickBite,
  'Лимон': faLemon,
  'Лимонный сок': faGlassWater,
  'Листы лазаньи': faBreadSlice,
  'Лосось': faFish,
  'Лук': faLeaf,
  'Лук красный': faLeaf,
  'Масло': faTint,
  'Мед': faIceCream,
  'Молоко': faGlassWater,
  'Морепродукты': faFish,
  'Морковь': faCarrot,
  'Мука': faMortarPestle,
  'Мясо': faDrumstickBite,
  'Нут': faSeedling,
  'Огурцы': faCarrot,
  'Оливки': faLeaf,
  'Оливковое масло': faTint,
  'Орехи': faSeedling,
  'Паприка': faPepperHot,
  'Пармезан': faCheese,
  'Пекинская капуста': faLeaf,
  'Перец': faPepperHot,
  'Перец чили': faPepperHot,
  'Петрушка': faLeaf,
  'Печенье савоярди': faCookie,
  'Помидоры': faAppleAlt,
  'Приправа': faMortarPestle,
  'Редька': faCarrot,
  'Рис': faSeedling,
  'Рисовая лапша': faSeedling,
  'Ростки бобов': faSeedling,
  'Салат': faLeaf,
  'Салат айсберг': faLeaf,
  'Сальса': faMortarPestle,
  'Сахар': faMortarPestle,
  'Свекла': faCarrot,
  'Свинина': faBacon,
  'Сливки': faGlassWater,
  'Соевый соус': faTint,
  'Соус': faMortarPestle,
  'Соус бешамель': faMortarPestle,
  'Соус терияки': faMortarPestle,
  'Сухарики': faBreadSlice,
  'Сыр': faCheese,
  'Сыр маскарпоне': faCheese,
  'Творог': faCheese,
  'Тесто': faBreadSlice,
  'Томатная паста': faAppleAlt,
  'Томатный соус': faAppleAlt,
  'Тортильи': faBreadSlice,
  'Тыква': faCarrot,
  'Укроп': faLeaf,
  'Утка': faDrumstickBite,
  'Фарш': faDrumstickBite,
  'Фасоль': faSeedling,
  'Фета': faCheese,
  'Хлеб': faBreadSlice,
  'Цыпленок': faDrumstickBite,
  'Чеснок': faPepperHot,
  'Шафран': faMortarPestle,
  'Шоколад': faCookie,
  'Яйца': faEgg
};
